### ISSUE TITLE
[examples] More detailed ts examles

### ISSUE THREAD

**Issue by dannystyleart** [kamilmysliwiec/nest-typescript-starter#1]
Hello @kamilmysliwiec ,

Could you provide more detailed examples for usage of framework in TS ? 

It would be cool to have a description of debugging the app when developed in ts and used with ts-node ( How do you use it?)

Some patterns would be also good for:
- A pattern for usage of an orm like Sequelize.js or mongodb
- A config pattern that is accessible from modules ( like loading config from file and share accross modules, components )

A better description, for authenticating roles before route controller would be hit would be welcomed.

Thanks in advance,
Danny

**Comment by adrien2p** [comment]
Hey, if you'd like to see how to implement sequelize with nest i can redirect you to my repo https://github.com/adrien2p/nest-js-sequelize-jwt
Let me a feedback if that help you

**Comment by kamilmysliwiec** [comment]
Hi,
Examples: https://github.com/kamilmysliwiec/nest/tree/master/examples
