### ISSUE TITLE
integrate with socket io

### ISSUE THREAD

**Issue by chaturanga836** [kamilmysliwiec/nest-typescript-starter#4]
Hi, I llike this frame work very much.. but im with trouble, how to config the socket io with the framework.. i try to use interface.. 

if you can give some example that is better

thank you

**Comment by kamilmysliwiec** [comment]
Hello,
Example: https://github.com/kamilmysliwiec/nest/tree/master/examples/02-gateways

**Comment by chaturanga836** [comment]
Hi Thank you,

but there is an issue on disconnect event, I try to do some operation by using disconnected user id, but it always returns last connected the user and also there is big memory leak it keeps all the sessions in socket session array didn't terminate.
